---
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "coronaschnell-server.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "coronaschnell-server.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/rewrite-target: /parse/$1
    nginx.ingress.kubernetes.io/default-backend: ingress-nginx-defaultbackend
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_cache_bypass                 $http_upgrade;
      proxy_set_header Connection        $connection_upgrade;
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
  tls:
    - secretName: {{ .Values.ingress.hostname }}
      hosts:
        - {{ .Values.ingress.hostname }}
{{- end }}
---
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "coronaschnell-server.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-exports
  labels:
    {{- include "coronaschnell-server.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/rewrite-target: /exports/$2
    nginx.ingress.kubernetes.io/default-backend: ingress-nginx-defaultbackend
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_cache_bypass                 $http_upgrade;
      proxy_set_header Connection        $connection_upgrade;
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /exports(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
  tls:
    - secretName: {{ .Values.ingress.hostname }}
      hosts:
        - {{ .Values.ingress.hostname }}
{{- end }}