---
{{- if .Values.maxUnavailable }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "prinoa-server.fullname" . }}
  labels:
    {{- include "prinoa-server.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "prinoa-server.selectorLabels" . | nindent 6 }}
{{- end }}
