chart-dirs:
  - charts
chart-repos:
  - mammut-helm=https://registry.mammut-hosting.de/artifactory/helm-charts
check-version-increment: true
debug: true
remote: origin
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true