apiVersion: v1
kind: Service
metadata:
  name: {{ include "e4f-server.fullname" . }}
  labels:
    {{- include "e4f-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port | default 4040 }}
      protocol: TCP
      name: http
  selector:
    {{- include "e4f-server.selectorLabels" . | nindent 4 }}
