{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "open-smart-city-server.fullname" . }}
  labels:
    {{- include "open-smart-city-server.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable | default "50%" }}
  selector:
    matchLabels:
      {{- include "open-smart-city-server.selectorLabels" . | nindent 6 }}
{{- end }}