apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-smart-city-server.fullname" . }}-env
type: Opaque
data:
  .env: >-
{{ .Files.Get "secrets/env/.env" | b64enc | indent 4 }}
---
{{- if .Values.server.github.private -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.server.github.sshSecret }}
data:
{{ (.Files.Glob "secrets/git-creds/*").AsSecrets | indent 2 }}
{{- end }}
---
{{- if .Values.server.parse.iosCert.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-smart-city-server.fullname" . }}-ios-cert
type: Opaque
data:
  ios_push_key.p8: >-
{{ .Files.Get "secrets/ios_push_key.p8" | b64enc | indent 4 }}
{{- end }}