apiVersion: v2
appVersion: '0.9.0'
description: A Helm chart for e4f-server
name: e4f-server
version: '0.9.4'
icon: https://docs.renovatebot.com/assets/images/logo.png
home: https://github.com/mammutmedia/e4f-server
sources:
  - https://github.com/mammutmedia/e4f-server
  - https://github.com/mammutmedia/helm-charts
maintainers:
  - name: Felix Nithammer
    email: f.nithammer@mammutmedia.eu
    url: https://mammutmedia.eu
annotations:
  artifacthub.io/license: AGPL-3.0-only
  artifacthub.io/images: |
    - name: e4f-server
      image: mammuthosting/e4f-server:0.9.0
  artifacthub.io/links: |
    - name: docs
      url: https://docs.renovatebot.com
