apiVersion: v1
kind: Service
metadata:
  name: {{ include "xerleben.fullname" . }}
  labels: {{- include "xerleben.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "xerleben.selectorLabels" . | nindent 4 }}
