{{- $svcPort := .Values.service.port -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myturn-eventbus.fullname" . }}
  labels:
    {{- include "myturn-eventbus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "myturn-eventbus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "myturn-eventbus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "myturn-eventbus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.env.secretName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port | default 1337 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port | default 1337 }}
            initialDelaySeconds: 10
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port | default 1337 }}
            initialDelaySeconds: 10
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
          {{- if .Values.dotEnvVault.enabled }}
            - mountPath: "/var/env-vault/env_vault"
              name: {{ .Values.dotEnvVault.secretName }}
              readOnly: true
          {{- end }}
            - name: {{ .Chart.Name }}-config
              mountPath: /usr/src/app/config
              readOnly: true
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - >
                    if [ -f "/var/env-vault/env_vault/.env.vault" ]; then
                      cp //var/env-vault/env_vault/.env.vault /usr/src/app/.env.vault;
                    fi;
      volumes:
        - name: {{ .Chart.Name }}-config
          secret:
            secretName: {{ .Values.config.secretName }}
      {{- if .Values.dotEnvVault.enabled }}
        - name: {{ .Values.dotEnvVault.secretName }}
          secret:
            secretName: {{ .Values.dotEnvVault.secretName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
