apiVersion: v1
kind: Service
metadata:
  name: {{ include "myturn-eventbus.fullname" . }}
  labels:
    {{- include "myturn-eventbus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1337
      protocol: TCP
      name: myturn-eventbus
  selector:
    {{- include "myturn-eventbus.selectorLabels" . | nindent 4 }}
