name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

  workflow_dispatch:

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2 #renovate: tag=v2.4.0
        with:
          fetch-depth: 0

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Install artifactory plugin
        run: helm plugin install https://github.com/belitre/helm-push-artifactory-plugin --version v1.0.1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Login to chart repo
        run: | 
          export HELM_EXPERIMENTAL_OCI=1
          echo ${{ secrets.REPO_TOKEN }} | helm registry login -u admin --password-stdin https://registry.mammut-hosting.de/helm-charts

      - name: Add mammut-helm repo
        run: echo ${{ secrets.REPO_TOKEN }} | helm repo add --username admin --password-stdin mammut-helm https://registry.mammut-hosting.de/artifactory/helm-charts

      - name: Run release script
        run: |
          chmod +x .github/release.sh
          ./.github/release.sh

      