name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1 #renovate: datasource=github-releases depName=helm lookupName=helm/helm

      - name: Add external Helm repos
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Build chart dependencies
        run: |
          for dir in charts/*/
          do
              (cd ${dir}; helm dependency build)
          done
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@c25b74a986eb925b398320414b576227f375f946 # renovate: tag=v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"