name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

  workflow_dispatch:

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct-install.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Install artifactory plugin
        run: helm plugin install https://github.com/belitre/helm-push-artifactory-plugin --version v1.0.1
        if: steps.list-changed.outputs.changed == 'true'

      - name: Login to chart repo
        run: | 
          export HELM_EXPERIMENTAL_OCI=1
          echo ${{ secrets.REPO_TOKEN }} | helm registry login -u admin --password-stdin https://registry.mammut-hosting.de/helm-charts
        if: steps.list-changed.outputs.changed == 'true'

      - name: Add mammut-helm repo
        run: echo ${{ secrets.REPO_TOKEN }} | helm repo add --username admin --password-stdin mammut-helm https://registry.mammut-hosting.de/artifactory/helm-charts
        if: steps.list-changed.outputs.changed == 'true'

      - name: Get changed charts
        run: IFS=$'\n' CHARTS=($(ct lsc))
        if: steps.list-changed.outputs.changed == 'true'

      - name: Package Charts
        run: |
          echo "Packaging this charts: ${CHARTS[@]}"
          for i in "${CHARTS[@]}"; do
            helm package $i
          done
        if: steps.list-changed.outputs.changed == 'true'

      - name: Upload Charts
        run: |
          echo "Uploading this charts: ${CHARTS[@]}"
          for j in *.tgz; do
            helm push-artifactory $j mammut-helm
          done
        if: steps.list-changed.outputs.changed == 'true'

      