name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.1 #renovate: datasource=github-releases depName=helm lookupName=helm/helm

      - name: Add external Helm repos
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Build chart dependencies
        run: |
          for dir in charts/*/
          do
              (cd ${dir}; helm dependency build)
          done
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@be16258da8010256c6e82849661221415f031968 # v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"