apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "osca-server.labels" . | nindent 4 }}
  name: {{ include "osca-server.metricsServiceName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.metrics.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: metrics-port
    port: {{ .Values.metrics.port }}
    targetPort: metrics-port
  selector:
    {{- include "osca-server.selectorLabels" . | nindent 4 }}
